In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [5]:
# create a 1-D array 
arr = np.array([1,3,5,53,6])
print(arr)

[ 1  3  5 53  6]


In [6]:
# create a 0-D array 
arr1 = np.array(3943)
arr1

array(3943)

In [7]:
# To check Deminsonal Array
arr.ndim

1

In [8]:
# To check Deminsonal Array
arr1.ndim

0

In [11]:
# creating a 2-D array
arr2 = np.array([[2,34,43,22,1],[3,43,2,2,2]])
print(arr2)

[[ 2 34 43 22  1]
 [ 3 43  2  2  2]]


In [13]:
# To check Deminsonal Array
print(arr2.ndim)

2


In [16]:
# number of elements
arr2.size


10

In [19]:
# Total memory taken by an array 
arr.nbytes

40

In [22]:
# single elements size
#[ 1  3  5 53  6]
arr.itemsize

8

In [23]:
# For the data type of the array
arr2.dtype

dtype('int64')

In [24]:
print(arr2)

[[ 2 34 43 22  1]
 [ 3 43  2  2  2]]


In [25]:
# For the specific elements of the array()
arr2[1,3]

2

In [27]:
# Specific row of the array
arr2[0,:]

array([ 2, 34, 43, 22,  1])

In [29]:
arr3 = np.array([3,4,5,2,32,21,3,4,3,2,24,4])
print(arr3)

[ 3  4  5  2 32 21  3  4  3  2 24  4]


In [32]:
# (Strat Index: Ending Index){inclusive:excusive}
print(arr3[3:6])

[ 2 32 21]


In [34]:
print(arr2)

[[ 2 34 43 22  1]
 [ 3 43  2  2  2]]


In [35]:
# Slicing for 2-D array
print(arr2[0,2:5])

[43 22  1]


In [36]:
# Copy of an array 
arr4 = arr2.copy()
print(arr4)

[[ 2 34 43 22  1]
 [ 3 43  2  2  2]]


In [38]:
# Zero Matrix
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [41]:
# All 1 Matrix
np.ones((3,4,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [46]:
# Other Matrix
np.full((3,5),45)


array([[45, 45, 45, 45, 45],
       [45, 45, 45, 45, 45],
       [45, 45, 45, 45, 45]])

In [47]:
# Impoprting random
from numpy import random

In [49]:
# To generate a random number
x = random.randint(99)
print(x)

95


In [51]:
# To generate a random Matrix
np.random.rand(4,4)

array([[0.68318308, 0.33734429, 0.09829344, 0.57877768],
       [0.52359098, 0.44271747, 0.57543663, 0.30462354],
       [0.69267166, 0.81053246, 0.84787613, 0.86061937],
       [0.10743081, 0.47618489, 0.7256881 , 0.30310279]])

In [52]:
# Identity Matrix 
np.identity(4)


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [53]:
# Mathsmatics Operation an array
arm = np.array([334,343,22,33])
print(arm)

[334 343  22  33]


In [56]:
# Add Operation
# Store array
arm = arm+10
print(arm)

[344 353  32  43]


In [57]:
# Subtract Operation
arm = arm-10
print(arm)

[334 343  22  33]


In [59]:
# Multiplication Operation
arm*2


array([668, 686,  44,  66])

In [60]:
# Divison Operation
arm/3

array([111.33333333, 114.33333333,   7.33333333,  11.        ])

In [63]:
# Addition of two Array
a1 = np.array([23,22,43,30])
a2 = np.array([34,33,32,21])
print(a1+a2)

[57 55 75 51]


In [64]:
# Cos Function in an Array
np.cos(a1)

array([-0.53283302, -0.99996083,  0.5551133 ,  0.15425145])

In [65]:
print(arr2)

[[ 2 34 43 22  1]
 [ 3 43  2  2  2]]


In [66]:
# For Minimun Array
np.min(arr2)

1

In [67]:
# For Maxmum Array
np.max(arr2)

43

In [68]:
# Sum of All matrix
np.sum(arr2)

154

In [70]:
# Iterating in 1-D
for e in a1:
    print(e)

34
33
32
21


In [71]:
# Iterating in 2-D
for q in arr2:
    print(q)

[ 2 34 43 22  1]
[ 3 43  2  2  2]


In [73]:
# Iterating in 2-D
for a in arr2:
    for b in a:
        print(b)

2
34
43
22
1
3
43
2
2
2
