In [4]:
pip install tensorflow

Note: you may need to restart the kernel to use updated packages.


In [6]:
import tensorflow as tf

2025-10-05 13:28:00.136815: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-10-05 13:28:00.193140: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-10-05 13:28:00.238788: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1759651080.284331    2959 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1759651080.299122    2959 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-10-05 13:28:00.396664: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU ins

In [7]:
mnist = tf.keras.datasets.mnist

(x_train, y_train),(x_test, y_test) = mnist.load_data()
x_train, x_test = x_train/255, x_test/255

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 5s 0us/step


In [8]:
model = tf.keras.models.Sequential([tf.keras.layers.Flatten(input_shape=(28,28)),
                                    tf.keras.layers.Dense(128, activation = 'relu'),
                                    tf.keras.layers.Dropout(0.2),
                                    tf.keras.layers.Dense(10)])

/home/hp/anaconda3/lib/python3.12/site-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)
2025-10-05 13:35:00.346235: E external/local_xla/xla/stream_executor/cuda/cuda_driver.cc:152] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)


In [11]:
predications = model(x_train[:1]).numpy()
predications

array([[-0.01276048,  0.04794323,  0.20676824,  0.4478199 , -0.52262175,
        -0.22980349, -0.31917623,  0.40182912, -0.33128047,  0.40909952]],
      dtype=float32)

In [13]:
tf.nn.softmax(predications).numpy() 

array([[0.09258923, 0.09838384, 0.11531892, 0.14675334, 0.05560714,
        0.07452464, 0.06815313, 0.1401569 , 0.06733316, 0.1411796 ]],
      dtype=float32)

In [14]:
loss_nf = tf.keras.losses.SparseCategoricalCrossentropy(from_logits= True) # actuall predication
loss_nf(y_train[:1], predications).numpy()

2.5966253

In [17]:
model.compile(optimizer='adam', loss = loss_nf, metrics = ['accuracy'])
model.fit(x_train, y_train, epochs = 5)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.8575 - loss: 0.4878
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9562 - loss: 0.1510
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9677 - loss: 0.1055
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9743 - loss: 0.0815
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9781 - loss: 0.0689


In [18]:
model.evaluate(x_test, y_test, verbose = 2) # To check the eaccuracy and loss of model

313/313 - 0s - 1ms/step - accuracy: 0.9767 - loss: 0.0735


[0.07351016253232956, 0.9767000079154968]

In [22]:
probabilaty_model = tf.keras.Sequential([model, tf.keras.layers.Softmax()]) # actuall predication of model
probabilaty_model(x_test[:3])

<tf.Tensor: shape=(3, 10), dtype=float32, numpy=
array([[6.2712957e-07, 1.2065629e-08, 8.5035372e-06, 7.5396069e-04,
        3.8120781e-11, 2.0248343e-07, 1.2862996e-11, 9.9922919e-01,
        1.0070872e-06, 6.3833636e-06],
       [7.0256125e-09, 2.8662520e-04, 9.9970740e-01, 3.8233256e-06,
        1.2728048e-16, 4.6181464e-07, 2.3128242e-08, 9.1870779e-14,
        1.6791163e-06, 4.7412278e-12],
       [4.6379944e-07, 9.9873728e-01, 1.8186370e-04, 7.5485573e-06,
        1.1545802e-04, 2.5815423e-06, 8.3144596e-06, 8.7668671e-04,
        6.9148176e-05, 5.8720281e-07]], dtype=float32)>

Keras

In [6]:
import sklearn
from sklearn.datasets import make_moons
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier, VotingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

In [7]:
x, y  = make_moons(n_samples = 500, noise = 0.32, random_state = 42)
x_train,  x_test, y_train, y_test = train_test_split(x,y , random_state = 42)

In [13]:
LogRefg_clf = LogisticRegression(solver = 'lbfgs', random_state = 42)
rnd_clf = RandomForestClassifier(n_estimators = 150 , random_state = 42)
svc_clf = SVC(gamma ='scale' , random_state = 42, probability = True)

from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

2025-10-05 17:20:23.276927: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-10-05 17:20:23.344481: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-10-05 17:20:23.398210: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1759665023.452023    3033 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1759665023.469399    3033 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-10-05 17:20:23.595212: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU ins

In [29]:
!pip install scikeras[tensorflow]


zsh:1: no matches found: scikeras[tensorflow]


In [30]:
pip install 'scikeras[tensorflow]'


Note: you may need to restart the kernel to use updated packages.


In [31]:
!pip install 'scikeras[tensorflow]'


In [15]:
def build_nn():
    model = Sequential([Dense(50, activation = 'relu', input_shape = [2]), Dense(1, activation = 'sigmoid')])
    model.complie(optimizer = 'Adam', loss = 'binary_crossentropy' , metrics = [accuracy])
    return model

In [36]:
!pip install 'scikeras[tensorflow]'


In [39]:
import tensorflow as tf
keras_tf = tf.keras.wrappers.KerasClassifier(build_fn=build_nn, epochs=500, verbose=0)

AttributeError: module 'keras.api.wrappers' has no attribute 'KerasClassifier'